export const INPUT_FOCUSED = 'INPUT_FOCUSED';
export const INPUT_BLURRED = 'INPUT_BLURRED';
export const INPUT_CHANGED = 'INPUT_CHANGED';
export const UPDATE_FOCUSED_SUGGESTION = 'UPDATE_FOCUSED_SUGGESTION';
