export const INPUT_FOCUSED = 'INPUT_FOCUSED';
export const INPUT_BLURRED = 'INPUT_BLURRED';
export const INPUT_CHANGED = 'INPUT_CHANGED';
export const UPDATE_FOCUSED_SUGGESTION = 'UPDATE_FOCUSED_SUGGESTION';
export const REVEAL_SUGGESTIONS = 'REVEAL_SUGGESTIONS';
export const CLOSE_SUGGESTIONS = 'CLOSE_SUGGESTIONS';
